name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy rustfmt
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt -- --check
      - name: Run clippy
        run: RUSTFLAGS='-D warnings' cargo clippy --all-targets
      - name: Run test
        run: cargo test --all-targets
